name: Go

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
 build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.0', '1.21.1', '1.21.2' ] # Add or remove versions as needed
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get dependencies
      run: go mod tidy && go mod download

    - name: Test
      run: go test -v ./...
